# Generated by Django 6.0.1 on 2026-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apt_number', models.IntegerField()),
                ('zip_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('registration_date', models.DateField()),
                ('party', models.TextField()),
                ('precinct', models.TextField()),
                ('v20', models.BooleanField()),
                ('v21_town', models.BooleanField()),
                ('v21_primary', models.BooleanField()),
                ('v22_general', models.BooleanField()),
                ('v23', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
