# Generated by Django 6.0.1 on 2026-03-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apt_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.IntegerField(),
        ),
    ]
