# Generated by Django 6.0.1 on 2026-03-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_apt_number_alter_voter_party_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='v20',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21_primary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21_town',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22_general',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23',
            field=models.TextField(),
        ),
    ]
