# Generated by Django 6.0.1 on 2026-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_v20_alter_voter_v21_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='party',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21_primary',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21_town',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22_general',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23',
            field=models.BooleanField(),
        ),
    ]
